spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/atelier_db
spring.datasource.username=atelier_user
spring.datasource.password=atelier_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true